package app

import (
	"bytes"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/XDuke/mini-singbox/internal/config"
	"github.com/XDuke/mini-singbox/internal/secret"
	"github.com/sagernet/sing-box/option"
)

func TestGenerateAllProtocolsAndValidate(t *testing.T) {
	output := filepath.Join(t.TempDir(), "generated")
	options := GenerateOptions{
		Output: output, Protocols: []string{"reality", "hy2", "anytls"}, Listen: "127.0.0.1",
		PublicAddress: "203.0.113.10",
		RealityPort:   20001, Hysteria2Port: 20002, AnyTLSPort: 20003,
		PublicRealityPort: 51165, PublicHysteria2Port: 25421, PublicAnyTLSPort: 36279,
		RealityServerName: "www.example.com", RealityHandshake: "www.example.com:443",
		TLSSAN: "server.example",
	}
	result, err := Generate(options)
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Files) != 10 {
		t.Fatalf("generated files = %v", result.Files)
	}
	loaded, err := config.DecodeFile(filepath.Join(output, "config.json"))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := config.Validate(loaded); err != nil {
		t.Fatal(err)
	}
	if !filepath.IsAbs(loaded.VLESSReality.PrivateKeyPath) || !filepath.IsAbs(loaded.Hysteria2.KeyPath) {
		t.Fatal("relative generated paths were not resolved against config directory")
	}
	var client clientInfo
	if err := json.Unmarshal(result.ClientInfo, &client); err != nil {
		t.Fatal(err)
	}
	if client.Hysteria2.Password == client.AnyTLS.Password {
		t.Fatal("Hysteria2 and AnyTLS passwords must differ")
	}
	if client.PublicAddress != options.PublicAddress {
		t.Fatalf("client delivery metadata = %#v", client)
	}
	if bytes.Contains(result.ClientInfo, []byte(`"subscription"`)) {
		t.Fatalf("client info unexpectedly contains subscription metadata: %s", result.ClientInfo)
	}
	assertShareURI(t, client.VLESSReality.ShareURI, "vless", options.PublicAddress, options.PublicRealityPort)
	assertShareURI(t, client.Hysteria2.ShareURI, "hysteria2", options.PublicAddress, options.PublicHysteria2Port)
	if !strings.Contains(client.Hysteria2.ShareURI, "insecure=1") ||
		!strings.Contains(client.Hysteria2.ShareURI, "pinSHA256=") {
		t.Fatalf("Hysteria2 share URI is not certificate-pinned: %s", client.Hysteria2.ShareURI)
	}
	if client.AnyTLS.ShareURI != "" {
		t.Fatalf("unsafe AnyTLS share URI was generated by default: %s", client.AnyTLS.ShareURI)
	}
	if client.AnyTLS.SingBoxOutboundFile != "client-anytls-sing-box-outbound.json" {
		t.Fatalf("AnyTLS authenticated client file = %q", client.AnyTLS.SingBoxOutboundFile)
	}
	if client.AnyTLS.MihomoProxyFile != "client-anytls-mihomo.yaml" ||
		client.AnyTLS.V2RayNShareFile != "share-anytls-v2rayn.txt" {
		t.Fatalf("AnyTLS client delivery files = %#v", client.AnyTLS)
	}
	assertAuthenticatedAnyTLSOutbound(t, filepath.Join(output, client.AnyTLS.SingBoxOutboundFile))
	assertAuthenticatedAnyTLSMihomo(t, filepath.Join(output, client.AnyTLS.MihomoProxyFile), client.AnyTLS.CertSHA, options.PublicAddress, options.PublicAnyTLSPort, client.AnyTLS.Password, client.AnyTLS.TLSSAN)
	assertAuthenticatedAnyTLSV2RayN(t, filepath.Join(output, client.AnyTLS.V2RayNShareFile), options.PublicAddress, options.PublicAnyTLSPort, client.AnyTLS.Password, client.AnyTLS.TLSSAN)
	if _, err := os.Stat(filepath.Join(output, "share-anytls.txt")); !os.IsNotExist(err) {
		t.Fatalf("unsafe AnyTLS share file exists by default: %v", err)
	}
	if _, err := Generate(options); err == nil || !strings.Contains(err.Error(), "already exists") {
		t.Fatalf("second Generate() error = %v", err)
	}
	options.Force = true
	if _, err := Generate(options); err != nil {
		t.Fatalf("forced Generate() error = %v", err)
	}
	entries, err := os.ReadDir(output)
	if err != nil {
		t.Fatal(err)
	}
	for _, entry := range entries {
		if strings.Contains(entry.Name(), ".tmp-") || strings.HasSuffix(entry.Name(), ".backup") {
			t.Fatalf("temporary file left behind: %s", entry.Name())
		}
	}
}

func assertAuthenticatedAnyTLSMihomo(t *testing.T, path, certificateSHA256, address string, port int, password, serverName string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{
		"type: anytls", `server: "` + address + `"`, "port: " + strconv.Itoa(port),
		`password: "` + password + `"`, `sni: "` + serverName + `"`,
		"skip-cert-verify: true", `fingerprint: "` + certificateSHA256 + `"`,
	} {
		if !bytes.Contains(content, []byte(expected)) {
			t.Fatalf("Mihomo AnyTLS delivery is missing %q: %s", expected, content)
		}
	}
}

func assertAuthenticatedAnyTLSV2RayN(t *testing.T, path, address string, port int, password, serverName string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	uri := strings.TrimSpace(string(content))
	const prefix = "v2rayn://anytls/"
	if !strings.HasPrefix(uri, prefix) {
		t.Fatalf("v2rayN AnyTLS URI = %q", uri)
	}
	payload, err := base64.RawURLEncoding.DecodeString(strings.TrimPrefix(uri, prefix))
	if err != nil {
		t.Fatal(err)
	}
	var profile struct {
		ConfigType     int    `json:"ConfigType"`
		CoreType       int    `json:"CoreType"`
		ConfigVersion  int    `json:"ConfigVersion"`
		Address        string `json:"Address"`
		Port           int    `json:"Port"`
		Password       string `json:"Password"`
		AllowInsecure  string `json:"AllowInsecure"`
		StreamSecurity string `json:"StreamSecurity"`
		SNI            string `json:"Sni"`
		Fingerprint    string `json:"Fingerprint"`
		Certificate    string `json:"Cert"`
	}
	if err := json.Unmarshal(payload, &profile); err != nil {
		t.Fatal(err)
	}
	if profile.ConfigType != 11 || profile.CoreType != 24 || profile.ConfigVersion != 4 ||
		profile.Address != address || profile.Port != port || profile.Password != password ||
		profile.AllowInsecure != "false" || profile.StreamSecurity != "tls" ||
		profile.SNI != serverName || profile.Fingerprint != "chrome" {
		t.Fatalf("v2rayN AnyTLS profile is incomplete or unsafe: %s", payload)
	}
	certificate, _ := pem.Decode([]byte(profile.Certificate))
	if certificate == nil || certificate.Type != "CERTIFICATE" {
		t.Fatal("v2rayN AnyTLS profile does not contain a PEM certificate")
	}
}

func TestGenerateInsecureAnyTLSShareRequiresExplicitOptIn(t *testing.T) {
	output := filepath.Join(t.TempDir(), "generated")
	result, err := Generate(GenerateOptions{
		Output: output, Protocols: []string{"anytls"}, Listen: "127.0.0.1",
		PublicAddress: "203.0.113.10", AnyTLSPort: 20003,
		TLSSAN: "server.example", AllowInsecureAnyTLSShare: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	var client clientInfo
	if err := json.Unmarshal(result.ClientInfo, &client); err != nil {
		t.Fatal(err)
	}
	assertShareURI(t, client.AnyTLS.ShareURI, "anytls", "203.0.113.10", 20003)
	if !strings.Contains(client.AnyTLS.ShareURI, "insecure=1") ||
		!strings.Contains(client.AnyTLS.ShareURI, "AnyTLS%20UNSAFE") {
		t.Fatalf("opt-in AnyTLS URI is not visibly marked unsafe: %s", client.AnyTLS.ShareURI)
	}
}

func assertAuthenticatedAnyTLSOutbound(t *testing.T, path string) {
	t.Helper()
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	var outbound struct {
		Type string                    `json:"type"`
		TLS  option.OutboundTLSOptions `json:"tls"`
	}
	if err := json.Unmarshal(content, &outbound); err != nil {
		t.Fatal(err)
	}
	if outbound.Type != "anytls" || !outbound.TLS.Enabled || outbound.TLS.ServerName == "" ||
		outbound.TLS.Insecure || len(outbound.TLS.Certificate) != 1 ||
		!strings.Contains(outbound.TLS.Certificate[0], "BEGIN CERTIFICATE") {
		t.Fatalf("AnyTLS outbound does not authenticate the server certificate: %s", content)
	}
	block, _ := pem.Decode([]byte(outbound.TLS.Certificate[0]))
	if block == nil || block.Type != "CERTIFICATE" {
		t.Fatal("AnyTLS outbound certificate is not PEM")
	}
	trustedCertificate, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatal(err)
	}
	roots := x509.NewCertPool()
	roots.AddCert(trustedCertificate)
	if _, err := trustedCertificate.Verify(x509.VerifyOptions{
		DNSName: outbound.TLS.ServerName, Roots: roots,
	}); err != nil {
		t.Fatalf("embedded AnyTLS certificate does not verify: %v", err)
	}
	attacker, err := secret.SelfSignedCertificate(outbound.TLS.ServerName, time.Now())
	if err != nil {
		t.Fatal(err)
	}
	attackerBlock, _ := pem.Decode(attacker.CertificatePEM)
	attackerCertificate, err := x509.ParseCertificate(attackerBlock.Bytes)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := attackerCertificate.Verify(x509.VerifyOptions{
		DNSName: outbound.TLS.ServerName, Roots: roots,
	}); err == nil {
		t.Fatal("a different self-signed AnyTLS certificate passed the embedded trust root")
	}
}

func TestGenerateRealityOnlyDoesNotRequireTLS(t *testing.T) {
	_, err := Generate(GenerateOptions{
		Output: filepath.Join(t.TempDir(), "generated"), Protocols: []string{"reality"}, Listen: "::1",
		RealityPort: 20001, RealityServerName: "www.example.com", RealityHandshake: "www.example.com:443",
	})
	if err != nil {
		t.Fatal(err)
	}
}

func assertShareURI(t *testing.T, value, scheme, host string, port int) {
	t.Helper()
	parsed, err := url.Parse(value)
	if err != nil {
		t.Fatal(err)
	}
	if parsed.Scheme != scheme || parsed.Hostname() != host || parsed.Port() != strconv.Itoa(port) {
		t.Fatalf("share URI = %s", value)
	}
}

func TestGenerateRejectsInvalidInputs(t *testing.T) {
	base := GenerateOptions{
		Output: filepath.Join(t.TempDir(), "generated"), Protocols: []string{"hy2"}, Listen: "127.0.0.1",
		Hysteria2Port: 20002, TLSSAN: "server.example",
	}
	tests := []struct {
		name string
		edit func(*GenerateOptions)
	}{
		{"unknown protocol", func(o *GenerateOptions) { o.Protocols = []string{"unknown"} }},
		{"hostname listen", func(o *GenerateOptions) { o.Listen = "localhost" }},
		{"bad port", func(o *GenerateOptions) { o.Hysteria2Port = 80 }},
		{"bad SAN", func(o *GenerateOptions) { o.TLSSAN = "bad_name" }},
		{"bad public address", func(o *GenerateOptions) {
			o.PublicAddress = "https://server.example"
		}},
		{"bad public port", func(o *GenerateOptions) {
			o.PublicAddress = "server.example"
			o.PublicHysteria2Port = 70000
		}},
		{"public port without address", func(o *GenerateOptions) {
			o.PublicHysteria2Port = 25421
		}},
		{"bad reality name", func(o *GenerateOptions) {
			o.Protocols = []string{"reality"}
			o.RealityPort = 20001
			o.RealityServerName = "bad_name"
			o.RealityHandshake = "www.example.com:443"
		}},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			options := base
			test.edit(&options)
			if _, err := Generate(options); err == nil {
				t.Fatal("Generate() unexpectedly succeeded")
			}
		})
	}
}

func TestGenerateRejectsConflictingPublicTCPPorts(t *testing.T) {
	_, err := Generate(GenerateOptions{
		Output:    filepath.Join(t.TempDir(), "generated"),
		Protocols: []string{"reality", "anytls"}, Listen: "127.0.0.1",
		PublicAddress: "server.example", PublicRealityPort: 443, PublicAnyTLSPort: 443,
		RealityPort: 20001, AnyTLSPort: 20003,
		RealityServerName: "www.example.com", RealityHandshake: "www.example.com:443",
		TLSSAN: "server.example",
	})
	if err == nil || !strings.Contains(err.Error(), "conflicts") {
		t.Fatalf("Generate() error = %v", err)
	}
}
